[project]
name="VietRAG-Embed-E5-Base"
version="0.1"
base_model="multilingal-e5-base"
dependencies = [
    "accelerate>=1.1.0",
    "transformers",
    "pandas",
    "pydantic",
    "datasets==3.6.0",
    "seacrowd>=0.2.2",
    "ipykernel>=7.3.0",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.2",
    "python-dotenv>=1.0",
    "pyarrow",
    "sentence_transformers",
    "faiss-cpu"
]
